//objet à exporter
export const dataTables = [
    {
        name: "Tiger Nixon",
        position: "System Architect",
        office: "Edinburgh",
        age: "61",
        startDate: "2011/04/25",
        salary: "$ 320,800",
    },
    {
        name: "Tiger Nixon",
        position: "System Architect",
        office: "Edinburgh",
        age: "61",
        startDate: "2011/04/25",
        salary: "$ 320,800",
    },
    {
        name: "Tiger Nixon",
        position: "System Architect",
        office: "Edinburgh",
        age: "61",
        startDate: "2011/04/25",
        salary: "$ 320,800",
    },
    {
        name: "Tiger Nixon",
        position: "System Architect",
        office: "Edinburgh",
        age: "61",
        startDate: "2011/04/25",
        salary: "$ 320,800",
    },
    {
        name: "Tiger Nixon",
        position: "System Architect",
        office: "Edinburgh",
        age: "61",
        startDate: "2011/04/25",
        salary: "$ 320,800",
    },
    {
        name: "Tiger Nixon",
        position: "System Architect",
        office: "Edinburgh",
        age: "61",
        startDate: "2011/04/25",
        salary: "$ 320,800",
    },
    {
        name: "Tiger Nixon",
        position: "System Architect",
        office: "Edinburgh",
        age: "61",
        startDate: "2011/04/25",
        salary: "$ 320,800",
    },
    {
        name: "Tiger Nixon",
        position: "System Architect",
        office: "Edinburgh",
        age: "61",
        startDate: "2011/04/25",
        salary: "$ 320,800",
    },
    {
        name: "Tiger Nixon",
        position: "System Architect",
        office: "Edinburgh",
        age: "61",
        startDate: "2011/04/25",
        salary: "$ 320,800",
    },
    {
        name: "Tiger Nixon",
        position: "System Architect",
        office: "Edinburgh",
        age: "61",
        startDate: "2011/04/25",
        salary: "$ 320,800",
    },
    {
        name: "Tiger Nixon",
        position: "System Architect",
        office: "Edinburgh",
        age: "61",
        startDate: "2011/04/25",
        salary: "$ 320,800",
    },
    {
        name: "Tiger Nixon",
        position: "System Architect",
        office: "Edinburgh",
        age: "61",
        startDate: "2011/04/25",
        salary: "$ 320,800",
    },
    {
        name: "Tiger Nixon",
        position: "System Architect",
        office: "Edinburgh",
        age: "61",
        startDate: "2011/04/25",
        salary: "$ 320,800",
    },
    {
        name: "Tiger Nixon",
        position: "System Architect",
        office: "Edinburgh",
        age: "61",
        startDate: "2011/04/25",
        salary: "$ 320,800",
    },
    {
        name: "Tiger Nixon",
        position: "System Architect",
        office: "Edinburgh",
        age: "61",
        startDate: "2011/04/25",
        salary: "$ 320,800",
    },
    {
        name: "Tiger Nixon",
        position: "System Architect",
        office: "Edinburgh",
        age: "61",
        startDate: "2011/04/25",
        salary: "$ 320,800",
    },
    {
        name: "Tiger Nixon",
        position: "System Architect",
        office: "Edinburgh",
        age: "61",
        startDate: "2011/04/25",
        salary: "$ 320,800",
    },
    {
        name: "Tiger Nixon",
        position: "System Architect",
        office: "Edinburgh",
        age: "61",
        startDate: "2011/04/25",
        salary: "$ 320,800",
    },
    {
        name: "Tiger Nixon",
        position: "System Architect",
        office: "Edinburgh",
        age: "61",
        startDate: "2011/04/25",
        salary: "$ 320,800",
    },
    {
        name: "Tiger Nixon",
        position: "System Architect",
        office: "Edinburgh",
        age: "61",
        startDate: "2011/04/25",
        salary: "$ 320,800",
    },
]