//objet à exporter
export const dataTables = [
    {
        name: "Tiger Nixon",
        position: "System Architect",
        office: "Edinburgh",
        age: "61",
        startDate: "2011/04/25",
        salary: "$ 320,800",
    },
    {
        name: "Garrett Winters",
        position: "Accountant",
        office: "Tokyo",
        age: "63",
        startDate: "2011/07/25",
        salary: "$ 170,750",
    },
    {
        name: "Ashton Cox",
        position: "Junior Technical Author",
        office: "San Francisco",
        age: "66",
        startDate: "2011/01/12",
        salary: "$ 320,800",
    },
    {
        name: "Cedric Kelly",
        position: "Senior Javascript Developer",
        office: "Edinburgh",
        age: "22",
        startDate: "2011/04/25",
        salary: "$ 433,060",
    },
    {
        name: "Airi Satou",
        position: "System Architect",
        office: "Edinburgh",
        age: "33",
        startDate: "201/03/24",
        salary: "$ 320,800",
    },
    {
        name: "Brielle Williamson",
        position: "Integratino Specialist",
        office: "Tokyo",
        age: "61",
        startDate: "2011/04/25",
        salary: "$ 320,800",
    },
    {
        name: "Tiger Nixon",
        position: "System Architect",
        office: "Edinburgh",
        age: "61",
        startDate: "2011/04/25",
        salary: "$ 320,800",
    },
    {
        name: "Tiger Nixon",
        position: "System Architect",
        office: "Edinburgh",
        age: "61",
        startDate: "2011/04/25",
        salary: "$ 320,800",
    },
    {
        name: "Tiger Nixon",
        position: "System Architect",
        office: "Edinburgh",
        age: "61",
        startDate: "2011/04/25",
        salary: "$ 320,800",
    },
    {
        name: "Tiger Nixon",
        position: "System Architect",
        office: "Edinburgh",
        age: "61",
        startDate: "2011/04/25",
        salary: "$ 320,800",
    },
    {
        name: "Tiger Nixon",
        position: "System Architect",
        office: "Edinburgh",
        age: "61",
        startDate: "2011/04/25",
        salary: "$ 320,800",
    },
    {
        name: "Tiger Nixon",
        position: "System Architect",
        office: "Edinburgh",
        age: "61",
        startDate: "2011/04/25",
        salary: "$ 320,800",
    },
    {
        name: "Tiger Nixon",
        position: "System Architect",
        office: "Edinburgh",
        age: "61",
        startDate: "2011/04/25",
        salary: "$ 320,800",
    },
    {
        name: "Tiger Nixon",
        position: "System Architect",
        office: "Edinburgh",
        age: "61",
        startDate: "2011/04/25",
        salary: "$ 320,800",
    },
    {
        name: "Tiger Nixon",
        position: "System Architect",
        office: "Edinburgh",
        age: "61",
        startDate: "2011/04/25",
        salary: "$ 320,800",
    },
    {
        name: "Tiger Nixon",
        position: "System Architect",
        office: "Edinburgh",
        age: "61",
        startDate: "2011/04/25",
        salary: "$ 320,800",
    },
    {
        name: "Tiger Nixon",
        position: "System Architect",
        office: "Edinburgh",
        age: "61",
        startDate: "2011/04/25",
        salary: "$ 320,800",
    },
    {
        name: "Tiger Nixon",
        position: "System Architect",
        office: "Edinburgh",
        age: "61",
        startDate: "2011/04/25",
        salary: "$ 320,800",
    },
    {
        name: "Tiger Nixon",
        position: "System Architect",
        office: "Edinburgh",
        age: "61",
        startDate: "2011/04/25",
        salary: "$ 320,800",
    },
    {
        name: "Tiger Nixon",
        position: "System Architect",
        office: "Edinburgh",
        age: "61",
        startDate: "2011/04/25",
        salary: "$ 320,800",
    },
]